<a href="https://colab.research.google.com/github/HuelFra/phyton/blob/main/Indexa%C3%A7%C3%A3o_Fatiamento_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
!pip install numpy

In [24]:
arr = np.arange(0,30,3)
arr[3]
arr[:5]
arr[2:]
arr[[0,5]]
arr[4:7]
arr[5:] = 100
arr_2d= np.arange(50).reshape([5,10])
arr_2d
arr_2d[0:3]
arr_2d[0:3, 0:3]
arr_2d[0:3,4:]
arr_2d
arr_2d > 20
boleano = arr_2d > 20
arr_2d[boleano]
np.logical_and(arr_2d >= 20, arr_2d <= 30)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [25]:
booleano = np.logical_and(arr_2d >= 20, arr_2d <= 30)
arr_2d[booleano]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
np.logical_or(arr_2d >= 20, arr_2d <= 30)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])