<a href="https://colab.research.google.com/github/HuelFra/phyton/blob/main/operacoes_com__arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
!pip install np



  Preparing metadata (setup.py) ... done
  Created wheel for np: filename=np-1.0.2-py3-none-any.whl size=13657 sha256=7efdadcfab77aedc7f7cea095d846a8cde2c4074c8b2cee7374a8427cd21c1cd
  Stored in directory: /root/.cache/pip/wheels/19/20/42/6ee214e617f78123903f603524d662ac6fa14154c3027fd992
Successfully built np


In [3]:
arr1 = np.arange(0,100,10)
arr2 = np.arange(0,50,5)

In [4]:
arr1

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
arr1 + arr2

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135])

In [7]:
arr1 - arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
arr1 * arr2

array([   0,   50,  200,  450,  800, 1250, 1800, 2450, 3200, 4050])

In [9]:
arr2 / arr1

<ipython-input-9-621d46aeda56>:1: RuntimeWarning: invalid value encountered in divide
  arr2 / arr1


array([nan, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [10]:
arr1 ** 2

array([   0,  100,  400,  900, 1600, 2500, 3600, 4900, 6400, 8100])

In [11]:
arr1 * 100

array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])

In [12]:
arr1 + 100

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [13]:
np.sqrt(arr1)

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532,
       7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])